### ISSUE TITLE
Problema no primeiro carregamento

### ISSUE THREAD

**Issue by jonatan2m** [JoicePaz/projetomatrix#14]
Detectei um problema no primeiro carregamento.
Abri o index.html e as imagens dos participantes não apareceu.
Depois de atualizar a página algumas  vezes, o conteúdo apareceu.
Pelo que vi, parece que o código do **efeito.js** está causando isso

**Comment by JoicePaz** [comment]
Resolvido! Obrigada pelo aviso ;)
